-- Enable UUID extension (optional, but good practice)
create extension if not exists "uuid-ossp";

-- Users table
create table public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text,
  phone text,
  name text not null,
  password_hash text not null,
  is_guest integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- User Profiles table
create table public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null unique,
  display_name text,
  age integer,
  current_module text default 'hallulu',
  total_stars integer default 0,
  total_practice_time real default 0,
  badges_earned text default '[]',
  unlocked_word_puzzles integer default 0,
  last_active timestamp with time zone
);

-- Grapheme Mastery table
create table public.grapheme_mastery (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  grapheme_id text not null,
  confidence_score real default 0,
  accuracy_rate real default 0,
  total_attempts integer default 0,
  successful_attempts integer default 0,
  consecutive_successes integer default 0,
  last_practiced timestamp with time zone,
  mastery_level text default 'not_started',
  average_response_time real,
  needs_adaptive_practice integer default 0,
  struggle_count integer default 0,
  unique(user_id, grapheme_id)
);

-- Practice Sessions table
create table public.practice_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  grapheme_id text not null,
  is_correct integer not null,
  response_time integer,
  puzzle_type text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Sessions table (for auth tokens)
create table public.sessions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  token text unique not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create indexes for performance
create index idx_users_username on public.users(username);
create index idx_sessions_token on public.sessions(token);
create index idx_mastery_user_id on public.grapheme_mastery(user_id);
create index idx_practice_user_id on public.practice_sessions(user_id);
